name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
#  IMAGE_NAME: ${{ secrets.DOCKER_HUB_REPOSITORY }}
   IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout paths
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            php:
              - 'php/**'
            php7:
              - 'php7/**'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image php8
        if: steps.changes.outputs.php == 'true'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            MAINTAINER=${{ github.repository_owner }}
            BRANCH=${{ github.ref_name }}
            SOURCE_COMMIT=${{ github.sha }}
          context: .
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64
          file: ./php82/Dockerfile
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
          tags: ghcr.io/${{ env.IMAGE_NAME }}/php-fpm:8.2
          push: true

      - name: Build and push Docker image php7
        if: steps.changes.outputs.php7 == 'true'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            MAINTAINER=${{ github.repository_owner }}
            BRANCH=${{ github.ref_name }}
            SOURCE_COMMIT=${{ github.sha }}
          context: .
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64
          file: ./php7/Dockerfile
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
          tags: ghcr.io/${{ env.IMAGE_NAME }}/php-fpm:7.2
          push: true
